import React from 'react';
import { 
  FileText, 
  Download, 
  Filter, 
  BarChart3, 
  PieChart, 
  Calendar,
  ChevronRight
} from 'lucide-react';

export default function Reports() {
  const reportTypes = [
    { title: 'Asset Inventory Report', description: 'Complete list of all assets with current status and valuation.', icon: FileText, color: 'bg-blue-50 text-blue-600' },
    { title: 'Maintenance History', description: 'Detailed log of all repairs and maintenance tasks performed.', icon: BarChart3, color: 'bg-green-50 text-green-600' },
    { title: 'Disposal Summary', description: 'Overview of retired assets and disposal reasons.', icon: PieChart, color: 'bg-red-50 text-red-600' },
    { title: 'Assignment Log', description: 'History of asset transfers between users and locations.', icon: Calendar, color: 'bg-amber-50 text-amber-600' },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-gray-900">Reports & Analytics</h2>
        <p className="text-gray-500">Generate and export detailed reports for compliance and auditing.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reportTypes.map((report, i) => (
          <div key={i} className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow group">
            <div className="flex items-start justify-between">
              <div className="flex items-start gap-4">
                <div className={cn("p-3 rounded-lg", report.color)}>
                  <report.icon size={24} />
                </div>
                <div>
                  <h3 className="font-bold text-gray-900 group-hover:text-blue-600 transition-colors">{report.title}</h3>
                  <p className="text-sm text-gray-500 mt-1 leading-relaxed">{report.description}</p>
                </div>
              </div>
              <button className="p-2 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg">
                <ChevronRight size={20} />
              </button>
            </div>
            <div className="mt-6 flex items-center gap-3">
              <button className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg font-bold text-sm hover:bg-blue-700 transition-colors">
                <Download size={16} />
                Generate PDF
              </button>
              <button className="flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-white border border-gray-200 text-gray-700 rounded-lg font-bold text-sm hover:bg-gray-50 transition-colors">
                <Download size={16} />
                Export CSV
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="p-6 border-b border-gray-100 flex items-center justify-between">
          <h3 className="font-bold text-gray-900">Recent Generated Reports</h3>
          <button className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-900">
            <Filter size={16} />
            Filter
          </button>
        </div>
        <div className="divide-y divide-gray-100">
          {[
            { name: 'Inventory_Q1_2024.pdf', type: 'Inventory', date: '2024-03-28', size: '2.4 MB', user: 'Admin' },
            { name: 'Maintenance_Log_March.csv', type: 'Maintenance', date: '2024-03-25', size: '1.1 MB', user: 'Admin' },
            { name: 'Disposal_Report_2023.pdf', type: 'Disposal', date: '2024-01-15', size: '4.8 MB', user: 'System' },
          ].map((file, i) => (
            <div key={i} className="p-4 flex items-center justify-between hover:bg-gray-50 transition-colors">
              <div className="flex items-center gap-4">
                <div className="p-2 bg-gray-100 rounded text-gray-500">
                  <FileText size={20} />
                </div>
                <div>
                  <h4 className="text-sm font-bold text-gray-900">{file.name}</h4>
                  <p className="text-xs text-gray-500">{file.type} • {file.size}</p>
                </div>
              </div>
              <div className="flex items-center gap-8">
                <div className="text-right hidden sm:block">
                  <p className="text-xs text-gray-500">Generated by</p>
                  <p className="text-sm font-medium text-gray-900">{file.user}</p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-gray-500">Date</p>
                  <p className="text-sm font-medium text-gray-900">{file.date}</p>
                </div>
                <button className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg">
                  <Download size={20} />
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

import { cn } from '../lib/utils';
